### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by xsznix** [vaguilar/js-y86#1]
Is there a license on this code?

I forked this like a year and a half ago and never thought anybody would take it too seriously but since then I've seen two downstream forks in the wild (by teachers/teaching assistants at actual universities!). I think it might be nice to explicitly specify a license. What do you think?

**Comment by vaguilar** [comment]
Oh wow, that's great. I've put the project under the MIT license and have added the license file to the repo. You should be able to do as you'd like with the code as long as you maintain attribution.
